### ISSUE TITLE
[windows] migration on windows 13-to-14 fails with `paramter is incorrect` message

### ISSUE THREAD

**Issue by whizzzkid** [ipfs/fs-repo-migrations#175] opened 2023-08-31 09:13 UTC
What should be the correct paramter?

```sh
Running migration fs-repo-13-to-14 ...
  => Running: C:\Users\User\AppData\Local\Temp\migrations3209015947\fs-repo-13-to-14.exe -path=C:\Users\User\.ipfs -verbose=true
The migrations of fs-repo failed:
  migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations3209015947\fs-repo-13-to-14.exe: The parameter is incorrect.
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
```

Source issues:

- https://github.com/ipfs/ipfs-desktop/issues/2607
- https://github.com/ipfs/ipfs-desktop/issues/2554

**Comment by lidel** [comment] 2023-09-25 13:06
@whizzzkid  maybe `-v`? 

```console
$ fs-repo-migrations --help                                                                                                                                                                 ~/tmp
Usage of fs-repo-migrations:
  -distpath string
    	specify the distributions build to use
  -revert-ok
    	allow running migrations backward
  -to string
    	repo version to upgrade to, or "latest" for latest repo version (default "latest")
  -v	print latest migration available and exit
  -y	answer yes to all prompts
```

**Comment by lidel** [comment] 2023-10-30 13:45
This is duplicate of  https://github.com/ipfs/fs-repo-migrations/issues/182#issuecomment-1724698461, let's continue with discussion/investigation there.

**Closed by lidel** 2023-10-30 13:45 UTC
Labels: need/triage
