### ISSUE TITLE
6-to-7 repo migration error

### ISSUE THREAD

**Issue by olizilla** [ipfs/fs-repo-migrations#79] opened 2018-08-20 12:02 UTC
I hit an error trying to upgrade my go-ipfs today.

```console
$ ipfs --version
ipfs version 0.4.14

$ ipfs update install v0.4.17
fetching go-ipfs version v0.4.17
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
  - Migration required
fetching fs-repo-migrations version v1.4.0
running migration: '/var/folders/gm/h2m4xm1d65d1yjbdz2v9kn5r0000gn/T/ipfs-update-migrate325778338/fs-repo-migrations -to 7 -y'
Found fs-repo version 6 at /Users/oli/.ipfs
===> Running migration 6 to 7...
applying 6-to-7 repo migration
ipfs migration:  migration 6 to 7 failed: cannot acquire lock: Lock FcntlFlock of /Users/oli/.ipfs/repo.lock failed: resource temporarily unavailable
ERROR: Migration Failed:  migration failed: exit status 1
install failed, reverting changes...
ERROR: migration failed: exit status 1 
Error: exit status 1
```

I've tried it with `ipfs daemon` running, not runnning, with sudo, without sudo. Is there anything else I should try or is there a bug I can help diagnose?

**Comment by schomatis** [comment] 2018-08-20 13:25
@olizilla Take a look at https://github.com/ipfs/go-ipfs/issues/5191#issuecomment-402830270 to see if it helps (this may be a duplicate of that closed issue, which, reading the final comments, I'm now thinking that maybe it should stay open).

**Comment by olizilla** [comment] 2018-08-20 13:38
Thanks @schomatis! I ran `ipfs-update install v0.4.17` and it worked.

**Comment by schomatis** [comment] 2018-08-20 13:41
Great, I'll close this issue (as it's indeed a duplicate of that one) and I'll ask there if that one could be reopened.

**Closed by schomatis** 2018-08-20 13:41 UTC
